---
manage_github_projects:
  description: Organize and manage GitHub projects to ensure timelines are met and tasks are properly assigned.
  expected_output: A well-organized project board with timelines and task assignments for each project.
  async_execution: false
  agent: github_manager
manage_repositories_and_issues:
  description: Oversee and manage repositories and issues within the organization
    to ensure they are well-structured and updated.
  expected_output: A report detailing the status of repositories and issues, including
    any updates or actions taken.
  async_execution:
  agent: repository_manager
verify_cohesion_of_organization:
  description: Review the organization's repositories, projects, and discussions to
    ensure they align with the overall goals and are cohesive.
  expected_output: An analysis report highlighting any cohesion issues and recommendations
    for improvements.
  async_execution:
  agent: organization_manager
